package fr.uphf.sae5a1api.controllers;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class RankingController {

    @GetMapping(value = "/ranking", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> ranking() {
        String json = """
        {
          "docs": [
            {
              "id": 122,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "METZ HANDBALL",
              "structure_id": 2662,
              "classement_place": 1,
              "classement_place_last_update": "2025-10-29T05:53:46.000Z",
              "evolution": 0,
              "classement_point_total": 21,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 7,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 0,
              "classement_but_plus": 277,
              "classement_but_moins": 151,
              "classement_difference": 126
            },
            {
              "id": 114,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "BREST BRETAGNE HANDBALL",
              "structure_id": 1791,
              "classement_place": 2,
              "classement_place_last_update": "2025-10-30T05:26:42.000Z",
              "evolution": 0,
              "classement_point_total": 21,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 7,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 0,
              "classement_but_plus": 254,
              "classement_but_moins": 165,
              "classement_difference": 89
            },
            {
              "id": 117,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "HANDBALL PLAN DE CUQUES",
              "structure_id": 3550,
              "classement_place": 3,
              "classement_place_last_update": "2025-10-30T05:26:42.000Z",
              "evolution": 0,
              "classement_point_total": 19,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 6,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 1,
              "classement_but_plus": 225,
              "classement_but_moins": 178,
              "classement_difference": 47
            },
            {
              "id": 126,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "OGC NICE COTE D'AZUR HANDBALL",
              "structure_id": 2129,
              "classement_place": 4,
              "classement_place_last_update": "2025-10-12T04:11:20.000Z",
              "evolution": 0,
              "classement_point_total": 17,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 5,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 2,
              "classement_but_plus": 183,
              "classement_but_moins": 193,
              "classement_difference": -10
            },
            {
              "id": 123,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "ST AMAND HANDBALL - PORTE DU HAINAUT",
              "structure_id": 2325,
              "classement_place": 5,
              "classement_place_last_update": "2025-10-27T05:17:20.000Z",
              "evolution": 0,
              "classement_point_total": 16,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 4,
              "classement_nbr_match_nul": 1,
              "classement_nbr_match_perdu": 2,
              "classement_but_plus": 192,
              "classement_but_moins": 191,
              "classement_difference": 1
            },
            {
              "id": 119,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "TOULON METROPOLE VAR HANDBALL",
              "structure_id": 3920,
              "classement_place": 6,
              "classement_place_last_update": "2025-10-27T05:17:20.000Z",
              "evolution": 0,
              "classement_point_total": 16,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 4,
              "classement_nbr_match_nul": 1,
              "classement_nbr_match_perdu": 2,
              "classement_but_plus": 187,
              "classement_but_moins": 188,
              "classement_difference": -1
            },
            {
              "id": 120,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "CHAMBRAY TOURAINE HANDBALL",
              "structure_id": 2010,
              "classement_place": 7,
              "classement_place_last_update": "2025-10-27T05:17:20.000Z",
              "evolution": 0,
              "classement_point_total": 14,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 3,
              "classement_nbr_match_nul": 1,
              "classement_nbr_match_perdu": 3,
              "classement_but_plus": 193,
              "classement_but_moins": 207,
              "classement_difference": -14
            },
            {
              "id": 124,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "JDA DIJON BOURGOGNE HANDBALL",
              "structure_id": 1720,
              "classement_place": 8,
              "classement_place_last_update": "2025-10-30T05:26:42.000Z",
              "evolution": 0,
              "classement_point_total": 13,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 3,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 4,
              "classement_but_plus": 178,
              "classement_but_moins": 181,
              "classement_difference": -3
            },
            {
              "id": 116,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "ES BESANCON FEMININ",
              "structure_id": 2394,
              "classement_place": 9,
              "classement_place_last_update": "2025-10-30T05:26:42.000Z",
              "evolution": 0,
              "classement_point_total": 13,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 3,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 4,
              "classement_but_plus": 196,
              "classement_but_moins": 202,
              "classement_difference": -6
            },
            {
              "id": 125,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "SAMBRE AVESNOIS HANDBALL",
              "structure_id": 2331,
              "classement_place": 10,
              "classement_place_last_update": "2025-10-11T04:46:20.000Z",
              "evolution": 0,
              "classement_point_total": 11,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 2,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 5,
              "classement_but_plus": 170,
              "classement_but_moins": 220,
              "classement_difference": -50
            },
            {
              "id": 115,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "PARIS 92",
              "structure_id": 3321,
              "classement_place": 11,
              "classement_place_last_update": "2025-10-26T04:09:28.000Z",
              "evolution": 0,
              "classement_point_total": 10,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 1,
              "classement_nbr_match_nul": 1,
              "classement_nbr_match_perdu": 5,
              "classement_but_plus": 162,
              "classement_but_moins": 192,
              "classement_difference": -30
            },
            {
              "id": 121,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "STELLA SAINT-MAUR HANDBALL",
              "structure_id": 3172,
              "classement_place": 12,
              "classement_place_last_update": "2025-10-26T04:09:28.000Z",
              "evolution": 0,
              "classement_point_total": 9,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 1,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 6,
              "classement_but_plus": 175,
              "classement_but_moins": 209,
              "classement_difference": -34
            },
            {
              "id": 118,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "STRASBOURG ACHENHEIM TRUCHTERSHEIM HANDBALL",
              "structure_id": 3987,
              "classement_place": 13,
              "classement_place_last_update": "2025-10-26T04:09:28.000Z",
              "evolution": 0,
              "classement_point_total": 9,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 1,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 6,
              "classement_but_plus": 168,
              "classement_but_moins": 204,
              "classement_difference": -36
            },
            {
              "id": 127,
              "poule_competition_id": 168256,
              "competition_engagement_equipe_libelle": "HAVRE ATHLETIC CLUB HB",
              "structure_id": 2897,
              "classement_place": 14,
              "classement_place_last_update": "2025-09-13T03:21:12.000Z",
              "evolution": 0,
              "classement_point_total": 7,
              "classement_nbr_match_joue": 7,
              "classement_nbr_match_gagne": 0,
              "classement_nbr_match_nul": 0,
              "classement_nbr_match_perdu": 7,
              "classement_but_plus": 188,
              "classement_but_moins": 267,
              "classement_difference": -79
            }
          ],
          "totalDocs": 14,
          "limit": 1000,
          "hasPrevPage": false,
          "hasNextPage": false,
          "page": 1,
          "totalPages": 1,
          "prevPage": null,
          "nextPage": null
        }
        """;
        return ResponseEntity.ok(json);
    }

}
